[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions" # para rotas serverless

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
